### ISSUE TITLE
gradlew with dos line endings

### ISSUE THREAD

**Issue by KotonBads** [PianoPenguin471/RavenWeave#12]
dos line endings makes the provided `gradlew` file not work at all and gives this error:
![image](https://github.com/PianoPenguin471/RavenWeave/assets/66117568/8f98ec7a-ddb7-41e2-971f-c34ac2c91719)

**Comment by Zircta** [comment]
Hello, I finally got around to trying to fix this. Only problem is I do not have a Linux system to test this on. So if you can download the [latest commit](https://github.com/PianoPenguin471/RavenWeave/tree/2a2788caa409316096d0aa245df70732c416d958) and tell me if it's fix I would appreciate it!

**Comment by KotonBads** [comment]
@Zircta yep can confirm it is indeed fixed. Thanks!
