### ISSUE TITLE
Freelook on hypixel

### ISSUE THREAD

**Issue by HierarchyMan** [PianoPenguin471/RavenWeave#15]
hitdelay fix and freelook on hypixel is the only reason i did weave loader
the original creator refuses to make freelook enabled on hypixel for weave
can you either add it to your raven weave or make a different weave mod that does that?

**Comment by normaluser12354** [comment]
you can use freelook just by when launmcing lunar turning off your internet then when the mc loads turning it back on

**Comment by HierarchyMan** [comment]
well it did work but not willing to do that every launch 
thanks for the trick

**Comment by Zircta** [comment]
Use a java agent for it

**Comment by Zircta** [comment]
^ I believe [LunarEnable](https://github.com/Nilsen84/lunar-client-agents/releases/tag/v1.2.0) still works, so that will let you use freelook on hypixel.
