### ISSUE TITLE
reach, esp color, cps

### ISSUE THREAD

**Issue by Lakymko** [PianoPenguin471/RavenWeave#3]
pls make reach work when u press the hotkey so it doesnt crash, esp color doesnt work, make the cps show on cps counter and keystrokes on lc, if possible w tap, s tap too
![image2](https://user-images.githubusercontent.com/131208826/232908399-b8c1f5fc-5871-4df7-a13d-813073bfda1b.png)

![image](https://user-images.githubusercontent.com/131208826/232908141-5ce72d81-bbb4-4759-8cd4-fa03d243743f.png)
pls fix this visual bug
when u change the value the "Mode: NORMAL" doesnt change, idk if it works cuz bridge assist doesnt work either,
![image](https://user-images.githubusercontent.com/131208826/232908669-2d39e5d3-aef3-484c-ae17-fb98ba4ddd40.png)
featureless button for "Sumo" doesnt work on normal b++ either pls just remove it

**Comment by Euro-pol** [comment]
velocity also not working

**Comment by anchit1234** [comment]
yes please fix velocity and block hit , W tap , S tap and Kill aura

**Comment by Euro-pol** [comment]
killaura works for me. check the targets maybe u set it wrong

**Comment by PianoPenguin471** [comment]
Killaura just doesn't render the target yet
________________________________

**Comment by Zircta** [comment]
This is all fixed
