### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Darkmonkey55** [PianoPenguin471/RavenWeave#32]
how to find the changelog ?

**Comment by Zircta** [comment]
No change log was included, but here is a list of the changes (may be missing a few changes)
1. Third Person Rotations
 - Vertical / Yaw rotations don't seem to work as expected though.
2. Added / Fixed Modules
 - BHop, Tracers
3. Removed Modules
 - AntiShuffle, Fullbright, SelfDestruct, CursorTrail, AutoHeader, AutoJump, Parkour, ChatLogger, Notifcations.
 - Don't feel sad, all of these modules didn't work.
4. GUI Bind Command
 - Usage: /gui {keybind}
5. Optimized File Size
 - 2.24 MB -> 1.5 MB.

**Comment by Darkmonkey55** [comment]
epic thanks
