### ISSUE TITLE
Antibot issue

### ISSUE THREAD

**Issue by DUELPVP** [PianoPenguin471/RavenWeave#38]
When you join a game, you will be sent onto the waiting platform. Then the Antibot scans all players as bots. So even if you toggle killaura, you still need to kill a player manually(with autoclicker or legit) to use the killaura. Or it won't attack anyone.

**Comment by Cosmic-SC** [comment]
what?

**Comment by Cosmic-SC** [comment]
turn off click only in aura options

**Comment by Zircta** [comment]
^ If you could provide a video or a deeper explanation that would be appreciated.

**Comment by DUELPVP** [comment]
The issue got resolved when I turned on "target naked" in target module. But it will targets NPCs in lobby then.

**Comment by PianoPenguin471** [comment]
The problem is that the antibot is outdated and doesn't filter out bots on most servers.
