### ISSUE TITLE
autoblock or any hud such as killaura hud or safewalk block display not working

### ISSUE THREAD

**Issue by Jooey233** [PianoPenguin471/RavenWeave#4]

**Comment by NerdHaxx** [comment]
its mixins this raven is based on b++ which used mixins & custom event system, however if mixins are not present the event system will not work just wait until they fix it or smth

**Comment by NerdHaxx** [comment]
edit: they have mixins but the build.gradle has nothing that would make the mixins work / execute

**Comment by PianoPenguin471** [comment]
> edit: they have mixins but the build.gradle has nothing that would make the mixins work / execute

Have you never heard of spongepowered mixins?

**Comment by Zircta** [comment]
This was fixed in beta 1.1, so this will be released soon

**Comment by NerdHaxx** [comment]
> > edit: they have mixins but the build.gradle has nothing that would make the mixins work / execute
> 
> Have you never heard of spongepowered mixins?

💀 understand how mixins work in a mod workspace first before saying random bs
